name: Deploy CI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Clean up repository
        run: |
          find . -maxdepth 1 ! -name '.github' ! -name '.git' ! -name '.' ! -name '..' -exec rm -rf {} \;
  
      - name: Clone rust-lang-uz/book
        run: git clone https://github.com/rust-lang-uz/book rust-book --depth 1
  
      # - name: Clone rust-lang-uz/rust-by-example
      #   run: git clone https://github.com/rust-lang-uz/rust-by-example rust-examples

      - name: Install mdbook
        run: |
          mkdir -p .tools
          curl -Lf https://github.com/rust-lang/mdBook/releases/download/v0.4.35/mdbook-v0.4.35-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./.tools
          ls -la .tools
          echo `pwd`/.tools >> $GITHUB_PATH

      - name: Build rust-book
        run: |
          mdbook build
          mv book ../../book
        working-directory: rust-book/rustbook-uz
  
      # - name: Build rust-examples
      #   run: |
      #     cd rust-examples
      #     mdbook build
      #     mv book ../rust-by-example
  
      - name: Clean up
        run: |
          rm -rf rust-book
          # rm -rf rust-examples
          rm -rf .tools
  
      - name: Copy files from base
        run: |
          ls -la .github/base
          cp -r .github/base .

      - name: Check for changes
        id: git-check
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          [[ -z $(git status -uno --porcelain) ]] && echo "this branch is clean, no need to push..." && echo "::set-output name=changes::false" && exit 0;
  
      - name: Commit and Push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git commit -m 'Update book and rust-examples $(date +%Y-%m-%d)'
          git push
  
